name: bacher
favicon: null
layout_spectrum: 0.7347684730775654
typography_spectrum: 0.23914843541570008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9322906783781946
  lightness: 0.6464087457861751
  saturation: 0.07481157290749252
  rhythmicContrast: 0.9747710034716874
purpose: []
